version: "3.9"
services:
  audetv:
    image: "traefik/whoami"
    networks:
      - traefik-public
      - default
    deploy:
      placement:
        constraints: [ node.labels.worker == worker-1 ]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.audetvRedirect.rule=Host(`fct-search.audetv.ru`) || Host(`www.fct-search.audetv.ru`)
        - traefik.http.services.audetvRedirect.loadBalancer.server.port=80
        - traefik.http.middlewares.audetvRedirect-redirect.redirectRegex.regex=^(https?://)(www.)?fct-search.audetv.ru/(.*)$$
        - traefik.http.middlewares.audetvRedirect-redirect.redirectRegex.replacement=$${1}svodd.ru/$${3}
        - traefik.http.middlewares.audetvRedirect-redirect.redirectRegex.permanent=true
        - traefik.http.routers.audetvRedirect.middlewares=audetvRedirect-redirect,secure-headers
        - traefik.http.routers.audetvRedirect.entryPoints=https
        - traefik.http.routers.audetvRedirect.tls=true
        - traefik.http.routers.audetvRedirect.tls.certResolver=letsEncrypt


networks:
  traefik-public:
    external: true
